version: "3.8"
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: localhost
    container_name: api_auditoria
    working_dir: /var/www
    volumes:
      - ../auditorias:/var/www
      - ./php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - api-auditoria
    ports:
      - "9000"
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql/
    ports:
      - "3306:3306"
    networks:
      - api-auditoria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_USER: auditoria
      MYSQL_PASSWORD: 123456789
      MYSQL_DATABASE: auditorias

  nginx:
    image: nginx:alpine
    container_name: nginx_auditoria
    restart: always
    ports:
      - 80:80
    volumes:
      - ../auditorias:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api-auditoria
  
networks:
  api-auditoria: